import type { Metadata } from "next";
import { Alexandria } from "next/font/google";
import "@/styles/globals.css";


const alexandria = Alexandria({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "EHACK",
  description: "Generated by EHACK",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={alexandria.className}>{children}</body>
    </html>
  );
}
