import type { Metadata } from "next";
import "@/styles/globals.css";
import { Suspense } from "react";
import Loading from "./loading";


export const metadata: Metadata = {
  title: "EHACK",
  description: "Generated by EHACK",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font">
          {children}
      </body>
    </html>
  );
}
